# -*- coding: utf-8 -*-
"""Generate the English nav_app_en.html from nav_app.html (Chinese). The data is numeric/base64 (no Chinese), so only UI strings are replaced.
After applying the ordered replacements, report any remaining Chinese (to help complete the table). pyenv."""
import re,sys
WEB=r"D:\Claude\SVI_FFW\output\step5_nav_webapp\webapp"
IN=sys.argv[1] if len(sys.argv)>1 else "nav_app.html"; OUT=sys.argv[2] if len(sys.argv)>2 else "nav_app_en.html"
html=open(f"{WEB}\\{IN}",encoding="utf-8").read()
html=html.replace('<html lang="zh">','<html lang="en">')
R=[
# ---- new rho/omega topology strings of the paper-routing build (nav_app_paper); placed first so they match first ----
# ---- paper build: lambda / exchange-rate panel + resistance rho distribution mode ----
("遮荫回报率 Shade reward(η)","Shade reward (η)"),
("当 λ 取默认值 0.2 时:遮荫回报率 η=λ/(1+λ)=<b>1/6</b>,即绕行只有在至少这一比例的额外路程转化为减少的日晒时才划算;<b>日晒 1 米 = 荫下 6.0 米</b>。例:1000 m 的路多绕 100 m,须至少少晒 17 m 才值得。","With the default λ=0.2: the shade reward η=λ/(1+λ)=<b>1/6</b> means a detour pays off only if at least this share of the extra distance converts into avoided sun; <b>1 m in the sun = 6.0 m in shade</b>. E.g. adding 100 m to a 1000 m walk pays off only if it avoids at least 17 m of sun."),
("路段成本 ωᵢ=ℓ×ρ 分布(λ='+PLAM+'):深=阻力大(晒),浅=阻力小(荫);最遮荫路 = min ω=Σℓ×ρ","Segment cost ωᵢ=ℓ×ρ (ρ=(1−σ)+λ, λ='+PLAM+'): dark = costly (long and sunny), light = cheap (short or shaded); coolest route = min ω=Σωᵢ"),
("路段成本 ωᵢ=ℓ×ρ(λ='+PLAM+')","Segment cost ωᵢ=ℓ×ρ (λ='+PLAM+')"),
("最遮荫路 = min ω=Σωᵢ","Coolest = min ω=Σωᵢ"),
(">全荫</span>",">all shade</span>"),
(">全晒</span>",">all sun</span>"),
(">路段成本 ωᵢ</button>",">Segment cost ωᵢ</button>"),
("步行人流量(论文口径 λ=","Pedestrian flow (paper, λ="),
("图1 · 路径级:点=OD,边=可行路径(互不交叉;越宽=权重越小=越优;路径权重 ω=Σℓ×((1−遮荫)+λ),λ='+PLAM+',coolest=min ω)","Graph 1 · Path level: nodes = O/D, edges = feasible paths (non-crossing; wider = lower weight = better; path weight ω = Σℓ×((1−shade)+λ), λ=0.2, coolest = min ω)"),
("图2 · 街道级:点=OD+道路交叉口,边=街道(越宽阻力越小;街道路权 ρ=(1−遮荫)+λ,λ='+PLAM+')","Graph 2 · Street level: nodes = O/D + road intersections, edges = streets (wider = lower resistance; street resistance ρ = (1−shade)+λ, λ=0.2)"),
("候选=λ扫描+迭代惩罚多样化(≤8 条代表性可行路径);阻力=论文口径(Fig4):街道路权 ρ=(1−遮荫)+λ(λ='+PLAM+',滑杆可调),路径权重 ω=Σℓ×ρ,coolest=min ω;仅阴影覆盖率+绕行率上限,不含拥挤度/遮荫连续性;点击弧线或行可在地图高亮(紫虚线)。","Candidates = λ sweep + iterative penalty diversification (≤8 representative feasible paths); resistance follows the paper (Fig4): street resistance ρ = (1−shade)+λ (λ='+PLAM+', set by the slider), path weight ω = Σℓ×ρ, coolest = min ω; shade coverage + detour cap only, no crowding/continuity; click an arc or row to highlight on the map (purple dashed)."),
("🕸 拓扑图 · OD 可行路径(ρ/ω)","🕸 Topology · OD feasible paths (ρ/ω)"),
("对比全设施基线:最优路权重 ω ","vs all-facility baseline: best-path weight ω "),
# ---- Class raster legend, 12 classes (wrapped in quotes to avoid substring collisions; placed first so they match first) ----
("遮荫来源分类","shade-source class"),
("日晒像素透明;组合=被多种同时遮挡","Sunlit pixels transparent; combos = shaded by several sources"),
("'建筑+树+连廊'","'Bldg+tree+link'"),
("'树+连廊+骑楼'","'Tree+link+arc'"),
("'建筑+连廊'","'Bldg+linkway'"),
("'树+连廊'","'Tree+linkway'"),
("'连廊+骑楼'","'Linkway+arcade'"),
("'树+骑楼'","'Tree+arcade'"),
("'建筑+树'","'Bldg+tree'"),
("'建筑阴影'","'Building'"),
("'树荫'","'Tree'"),
("'连廊荫'","'Linkway'"),
("'骑楼走道'","'Arcade'"),
("'建筑底座'","'Building base'"),
# ---- topology module + facility scenarios (long strings first; exact match with JS context) ----
("候选=λ扫描+迭代惩罚多样化(≤8 条代表性可行路径,穷举为指数级不可行);拥挤度=沿路人流均值(按候选集内最大值归一);连续日晒=最长连续日晒段长度占比(边遮荫<50% 记日晒);点击弧线或行可在地图高亮(紫虚线)。权重为专家设定值(文献无公认四因子权重;遮荫相关合计 50%/60%,参照 CoolWalks 单参数避晒范式)。","Candidates = lambda sweep + iterative penalty diversification (<=8 representative feasible paths; full enumeration is exponential); crowding = mean pedestrian flow along the path (normalized by the max within the candidate set); continuous sun = longest continuous sun-exposed stretch as a share of length (edge shade <50% counts as sun); click an arc or row to highlight it on the map (purple dashed). Weights are expert-set (no canonical four-factor weights in the literature; shade-related terms total 50%/60%, cf. the CoolWalks single-parameter sun-aversion paradigm)."),
("图1 · 路径级:点=OD,边=可行路径(互不交叉;越宽阻力越小;W=0.2拥挤+0.3(1−遮荫)+0.3绕行+0.2连续日晒)","Graph 1 · Path level: nodes = O/D, edges = feasible paths (non-crossing; wider = lower resistance; W = 0.2 crowding + 0.3 (1−shade) + 0.3 detour + 0.2 continuous-sun)"),
("图2 · 街道级:点=OD+道路交叉口,边=街道(越宽阻力越小;W=0.4拥挤+0.6(1−遮荫))","Graph 2 · Street level: nodes = O/D + road intersections, edges = streets (wider = lower resistance; W = 0.4 crowding + 0.6 (1−shade))"),
(" — 其中线边禁行,其下路段遮荫回退为仅建筑+树(Coolest/卡片/剖面/拓扑图同步重算)"," — centerline edges banned; shade under them falls back to buildings+trees only (Coolest / cards / profile / topology all recompute)"),
("设施场景:全设施(骑楼+连廊计入寻路与遮荫)","Facility scenario: all facilities (arcades + linkways count in routing & shade)"),
("设施场景:已移除 ","Facility scenario: removed "),
("(!SCN.arc&&!SCN.lkw?'骑楼+连廊':(!SCN.arc?'骑楼':'连廊'))","(!SCN.arc&&!SCN.lkw?'arcades+linkways':(!SCN.arc?'arcades':'linkways'))"),
("?'已移除 骑楼+连廊':(!SCN.arc?'已移除 骑楼':'已移除 连廊')","?'Removed arcades+linkways':(!SCN.arc?'Removed arcades':'Removed linkways')"),
("?'全设施':","?'All facilities':"),
("OD 间可行路径拓扑图(绕行率上限=My Demos 的 Detour limit)","OD feasible-path topology graph (detour cap = the Detour limit in My Demos)"),
("请先点出起终点(或用 Demo)算出路径,再开拓扑图","Set origin & destination first (or use a demo) to compute a route, then open the topology graph"),
(" 条(勾/取消左侧 Arcades / Covered linkways 图层对比)"," (tick / untick the Arcades & Covered linkways layers to compare)"),
("对比全设施基线:最优路阻力 W ","vs all-facility baseline: best-path resistance W "),
("纯最遮荫路(λ=0)的绕行率 = 可行谱系上界;Detour limit 高于它后再调大,图形不会变化","Detour ratio of the pure most-shaded path (lam=0) = upper bound of the feasible spectrum; raising the Detour limit beyond it no longer changes the graph"),
(">谱系上界 '",">spectrum cap '"),
("🕸 拓扑图 · OD 可行路径","🕸 Topology · OD feasible paths"),
("tip('两点不在同一连通区域')","tip('The two points are not in the same connected area')"),
("拓扑计算中…","Computing topology…"),
(">拓扑图</button>",">Topology</button>"),
("场景:<b>","Scenario: <b>"),
("</b> · 绕行率上限 ","</b> · detour cap "),
("× · 可行路径 ","× · feasible paths "),
("</span> · 可行路径 ","</span> · feasible paths "),
("</b> · 可行路径 ","</b> · feasible paths "),
(" 条</div>"," routes</div>"),
(") · 遮荫 ",") · shade "),
("m · 遮荫 ","m · shade "),
(" · 拥挤 "," · crowding "),
(" · 绕行 "," · detour "),
("x · 最长连续日晒 ","x · longest continuous sun "),
("<title>街道 ","<title>Street "),
("m · 遮荫'","m · shade'"),
("% · 拥挤'","% · crowding'"),
(" · 绕行'"," · detour'"),
("× · 连续日晒'","× · continuous sun'"),
("(最短)","(shortest)"),
(">卫星</button>",">Satellite</button>"),
("HDB 架空层","HDB stilt floor"),
("已自动隐藏路网着色以突出 OD 路线(可在 Network view 重新开启)","Network colouring auto-hidden to highlight the OD routes (re-enable in Network view)"),
("已切到「分类高亮」:红=骑楼 蓝=连廊 青=过街天桥 橙=楼宇连廊 紫=接入桥 · 已自动干净展示:Simple 底图 · 2D · 关太阳阴影 · Routes Hide(均可手动改回)","Switched to By-type — red=Arcade, blue=Linkway, teal=Covered bridge, orange=Inter-building corridor, purple=Bridge link · Clean display auto-set: Simple basemap · 2D · sun shadow off · Routes Hide (all adjustable)"),
("已切到「统一高亮」,设施统一洋红 · 已自动干净展示:Simple 底图 · 2D · 关太阳阴影 · Routes Hide(均可手动改回)","Switched to Uniform — facilities all magenta · Clean display auto-set: Simple basemap · 2D · sun shadow off · Routes Hide (all adjustable)"),
("已自动干净展示:Simple 底图 · 2D · 关太阳阴影 · Routes Hide(均可手动改回)","Clean display auto-set: Simple basemap · 2D · sun shadow off · Routes Hide (all adjustable)"),
("步行人流量(避热 τ=","Pedestrian flow (heat-avoiding τ="),
("步行人流量(原始网络)","Pedestrian flow (original network)"),
(">速度(×步速)</span>",">Speed (× walk)</span>"),
# ---- results panel: shade contribution share of artificial facilities (arcades / linkways) (strings carry JS context so nothing else is hit) ----
("// 骑楼(3)/连廊(4)对路径总遮荫的贡献占比,口径同剖面:每边遮荫米数 EL×ES/100,分母=路径总遮荫米数(=shade×len)","// arcade(3)/linkway(4) share of path total shade; same metric as the profile: per-edge shaded metres EL×ES/100, denominator=path total shaded metres (=shade×len)"),
("骑楼段沿路提供遮荫约 ","Arcade shade along route ~"),
("有盖连廊段沿路提供遮荫约 ","Covered linkway shade along route ~"),
("人工设施遮荫贡献 <b","Facility shade <b"),
(">骑楼 '+Math.round(f.arc*100)",">Arcade '+Math.round(f.arc*100)"),
(">连廊 '+Math.round(f.lkw*100)",">Linkway '+Math.round(f.lkw*100)"),
("(合计 '+Math.round((f.arc+f.lkw)","(total '+Math.round((f.arc+f.lkw)"),
# ---- 3D / pedestrian-view new UI (long strings first, so short words don't break them) ----
("3D 鸟瞰:拖拽旋转、右键调俯仰;半透明楼 + 骑楼架空体 + 连廊挑板(勾「3D 树木」看真树)","3D aerial: drag to rotate, right-drag to pitch; translucent buildings + arcade elevated body + linkway cantilever (tick 3D trees to see real trees)"),
("太阳阴影:three.js 真实投射(视野内建筑/骑楼/树,随时刻),缩放到街区看,拖时刻滑杆影子转","Sun shadow: three.js real casting (in-view buildings/arcades/trees, by hour); zoom to street level, drag the time slider to rotate shadows"),
("行人视角:上=最遮荫 下=最短;各自 ▶ 单独播,或「同步播放」一起走(同速率,短路先到);拖时刻滑杆变太阳","Pedestrian view: top = Coolest, bottom = Shortest; ▶ play each solo, or Sync-play together (same speed, shorter finishes first); drag the time slider to move the sun"),
("请先点出起终点(或用 Demo)算出路径,再开行人视角","Set an origin and destination first (or use a demo) to compute a route, then open the pedestrian view"),
("3D 真树已开:缩放到街区(zoom≥13,2D/3D 视图都可)显示视野内真树","3D real trees on: zoom to street level (zoom>=13, in 2D or 3D) to show in-view trees"),
("先切到 3D 鸟瞰再比较骑楼柱子","Switch to 3D aerial first to compare arcade columns"),
("请先切到「3D 鸟瞰」再开 3D 树木","Switch to 3D aerial first, then enable 3D trees"),
("请先切到「3D 鸟瞰」再开太阳阴影","Switch to 3D aerial first, then enable sun shadow"),
("骑楼=架空柱廊(底层显柱子 + 上方悬体)","Arcade = elevated colonnade (columns below + suspended body above)"),
("骑楼=悬浮体(底层透空,不画柱)","Arcade = suspended body (open below, no columns)"),
("骑楼柱子:开(鸟瞰 + 行人视角骑楼下都显柱)","Arcade columns: ON (columns under arcades in both aerial and pedestrian views)"),
("骑楼柱子:关(悬浮体,底层透空)","Arcade columns: OFF (suspended body, open below)"),
("three.js 未加载(需联网),3D 树木不可用","three.js not loaded (needs internet) — 3D trees unavailable"),
("three.js 未加载(需联网),行人视角不可用","three.js not loaded (needs internet) — pedestrian view unavailable"),
("或各自 ▶ 单独播 · 灰建筑 绿树 红棕骑楼 蓝连廊","Or ▶ play each solo · gray buildings, green trees, rust arcades, blue linkways"),
("逐时太阳遮荫(随时刻滑杆)","Hourly sun shade (by time slider)"),
("骑楼柱廊柱子(仅3D)","Arcade colonnade columns (3D only)"),
("行人视角 · Coolest/Shortest 对比","Pedestrian view · Coolest / Shortest"),
("最遮荫 Coolest","Coolest (most shaded)"),
("最短 Shortest","Shortest"),
("已切回 2D 平面","Back to 2D flat"),
("3D 树木已关","3D trees off"),
("太阳阴影已关","Sun shadow off"),
("⏸ 全部暂停","⏸ Pause all"),
("同步播放","Sync play"),
("时序路径阴影","Path shade over distance"),
("视图 View","View"),
("</span>3D 树木</label>","</span>3D trees</label>"),
("2D 平面","2D flat"),
("3D 鸟瞰","3D aerial"),
("骑楼柱子","Arcade columns"),
("行人视角","Pedestrian view"),
("太阳阴影","Sun shadow"),
("绕行阈值 Detour limit","Detour limit"),
("我的 Demo(收藏 / 导入导出)","My Demos (saved / import & export)"),
("已切到「仅原始人行道」,隐藏了设施小微网","Switched to Original — facility micro-net hidden"),
("已切到「分类高亮」:红=骑楼 蓝=连廊 青=过街天桥 橙=楼宇连廊 紫=接入桥","Switched to By-type — red=Arcade, blue=Linkway, teal=Covered bridge, orange=Inter-building corridor, purple=Bridge link"),
("已切到「统一高亮」,设施统一洋红","Switched to Uniform — facilities all magenta"),
("已切到「全部路网」","Switched to All network"),
('<br><span class="sw" style="background:#d6336c"></span>骑楼 &nbsp;<span class="sw" style="background:#2b6cb0"></span>连廊 &nbsp;<span class="sw" style="background:#12a5b0"></span>过街天桥 &nbsp;<span class="sw" style="background:#e07b2a"></span>楼宇连廊 &nbsp;<span class="sw" style="background:#9b59b6"></span>接入桥','<br><span class="sw" style="background:#d6336c"></span>Arcade &nbsp;<span class="sw" style="background:#2b6cb0"></span>Linkway &nbsp;<span class="sw" style="background:#12a5b0"></span>Covered bridge &nbsp;<span class="sw" style="background:#e07b2a"></span>Inter-building corridor &nbsp;<span class="sw" style="background:#9b59b6"></span>Bridge link'),
("遮荫率(纵)×归一化行程(横)","shade % (y) x normalized trip (x)"),
("遮荫率(纵)×实际距离(横)","shade % (y) × distance in m (x)"),
("上带=最遮荫路设施,中带=最短路设施","top band = Coolest facilities, mid band = Shortest facilities"),
("归一化行程→","normalized trip →"),
("按住标题拖动 · 拖右下角缩放","Drag title to move · drag corner to resize"),
("遮荫栅格(14:00,1m 瓦片)","Shade raster (14:00, 1m tiles)"),
("遮荫栅格 (10m)","Shade raster (10m res.)"),
("阴影 Shadow(随滑杆)","Shadow"),
("分类 Category(随滑杆)","Class"),
("逐时 8–18点 · 阴影/分类栅格 + 设施人流 ","Hourly 08–18 · shadow/class raster + facility flow "),
("点击地图设起点/终点。最遮荫路=最小日晒里程;最短路=最短距离。栅格已内联(树木/阴影/分类均 ≈10m 单帧),双击即可打开,无需服务器。","Click the map to set origin/destination. Coolest = least sun-exposed distance; Shortest = shortest distance. Rasters are inlined (trees/shadow/class ~10m single frame) — open by double-click, no server needed."),
("遮荫栅格(40m 逐时,8–18点 ","Shade raster (40m hourly, 08–18 "),
("逐时阴影 Shadow","Hourly shadow"),
("逐时分类 Category","Hourly class"),
("点击地图设起点/终点。最遮荫路=最小日晒里程;最短路=最短距离。栅格已内联(树木≈10m、阴影/分类≈40m 逐时),双击即可打开,无需服务器。","Click the map to set origin/destination. Coolest = least sun-exposed distance; Shortest = shortest distance. Rasters are inlined (trees ~10m, shadow/class ~40m hourly) — open by double-click, no server needed."),
("const FACNM={0:'日晒',1:'建筑',2:'树木',3:'骑楼',4:'连廊',5:'建筑内部'}","const FACNM={0:'Sun',1:'Building',2:'Tree',3:'Arcade',4:'Linkway',5:'Indoor'}"),
("路径阴影剖面","Path shade profile"),
("最遮荫路 · 遮荫率(纵)× 距离(横),底色=主导遮荫设施","Coolest route · shade % (y) × distance (x); background = dominant shade facility"),
("?'骑楼':'有盖连廊'","?'Arcade':'Covered linkway'"),
(" · 服务人流 ≈ "," · serves ≈ "),
(" 人 ("," ppl ("),
(">灰<",">Gray<"),
("逐时概览(40m,8–18点 ","Hourly overview (40m, 08–18 "),
("逐时阴影概览","Hourly shadow (overview)"),
("逐时分类概览","Hourly class (overview)"),
("14:00 路段遮荫率(蓝=遮荫,红=日晒)","14:00 path shade (blue=shaded, red=sun)"),
("路网(无色)","Network (plain)"),
("路网线","network line"),
("无色","Plain"),
("可选起讫点(点击设起/终点)","Selectable O/D points (click to set)"),
("站点 MRT/巴士","Stations (MRT / bus)"),
("建筑中心点","Building centroids"),
("工作日客流 ","weekday flow "),
("巴士 ","Bus "),
("14:00 阴影 Shadow(深=遮荫强)","14:00 shadow (deeper = more shade)"),
("14:00 阴影分类 Category","14:00 shadow class"),
("树木(树冠高度)","Trees (canopy height)"),
("点击地图设起点/终点。最遮荫路=最小日晒里程;最短路=最短距离。栅格为真 1m(z18)瓦片:树木深浅=树冠高度、阴影深浅=遮荫强度、分类=类别色;需经本地服务器打开。","Click the map to set origin/destination. Coolest = least sun-exposed distance; Shortest = shortest distance. Rasters are true-1m (z18) tiles: tree shade = canopy height, shadow shade = shading intensity, category = class colour. Open via a local server."),
("点击地图设起点/终点。最遮荫路=最小日晒里程;最短路=最短距离。矢量层 GPU 渲染,任意缩放清晰。","Click the map to set origin/destination. Coolest = least sun-exposed distance; Shortest = shortest distance. Vector layers are GPU-rendered — crisp at any zoom."),
("MapLibre 矢量 · 新加坡全城真实步行网络 · 14:00 · 实时路由","MapLibre vector · Singapore citywide pedestrian network · 14:00 · live routing"),
("蔭径 · 避热导航 (MapLibre 矢量)","ShadeWalk · Heat-Avoidance Navigation (MapLibre vector)"),
("两点不在同一连通区域。","These two points are not in the same connected area."),
("遮荫设施图层","Shade-facility layers"),
("逐时栅格(整点 ","Hourly raster (hour "),
("建筑","Buildings"),
("骑楼 arcade","Arcades"),
("有盖连廊","Covered linkways"),
("逐时阴影 Shadow","Hourly shadow"),
("阴影分类 Category","Shadow class (Category)"),
("网络视图","Network view"),
("路网已隐藏","Network hidden"),
("起点:已选","Origin set"),("终点:已选","Destination set"),
("起点:示例","Origin: demo"),("终点:示例","Destination: demo"),
("// 路由图","// routing graph"),("// 网络分箱 MultiLineString","// binned network"),
("隐藏","Hide"),
("点击地图设起点/终点(自动吸附最近路口)。最遮荫路=最小日晒里程;最短路=最短距离。逐时栅格随整点滑条切换(7:00–19:00);路由/网络着色按 14:00。",
 "Click the map to set origin/destination (snaps to nearest junction). Coolest = least sun-exposed distance; Shortest = shortest distance. The hourly raster switches with the slider (08:00–18:00); routing & network colour are for 14:00."),
("两点不在同一连通区域,无法步行抵达。","These two points are not in the same connected area — no walking route."),
("新加坡全城真实步行网络 · 14:00 最热时段 · 内置实时路由","Singapore citywide pedestrian network · 14:00 peak heat · built-in live routing"),
("蔭径 · 避热出行导航(全城真实路网)","ShadeWalk · Heat-Avoidance Navigation (citywide network)"),
("遮荫设施图层(可分别叠加)","Shade-facility layers (toggle separately)"),
("逐时阴影 Shadow(蓝=遮荫)","Hourly shadow (blue = shaded)"),
("阴影分类 Category","Shadow class (Category)"),
("逐时栅格图层(整点 ","Hourly raster (hour "),
("底图瓦片 Basemap","Basemap"),
("树木 (10m)","Trees (10m res.)"),
("建筑(footprint)","Buildings (footprint)"),
("骑楼 arcade","Arcades (five-foot way)"),
("有盖连廊 covered linkway","Covered linkways"),
("避热选最遮荫路:遮荫 +","Coolest route: +"),
(" 个百分点,绕行 "," pts more shade, +"),
("%(多走 ","% detour (extra "),
(" m)。"," m)."),
("起点:点击地图选择","Origin: tap on map"),
("终点:再次点击地图","Destination: tap again"),
("起点:已选(路口 #","Origin set (node #"),
("终点:已选(路口 #","Destination set (node #"),
("起点:示例站点","Origin: demo station"),
("终点:示例站点","Destination: demo station"),
("14:00 路段遮荫率","14:00 path shade %"),
("步行人流量","Pedestrian flow"),
("高遮荫","high shade"),
("最遮荫路","Coolest"),("最短路","Shortest"),
("路段遮荫率","path shade %"),
("遮荫率","Shade"),
("人流量","Pedestrian flow"),
("最遮荫","Coolest"),("最短","Shortest"),
("两者","Both"),("极简","Minimal"),("显示路线","Routes"),("底图着色","Network colour"),
(" 骑楼 "," Arcade "),(" 树木 "," Trees "),(" 连廊/低棚 "," Linkway/shelter "),(" 建筑"," Building"),
(" 示例"," Demo"),(" 清除"," Clear"),(" 互换"," Swap"),
("蔭径 · 避热导航","ShadeWalk"),
("计算中…","Computing…"),
("分钟","min"),
("请先点出起讫点(或选个示例)再保存","Click an origin & destination (or pick a demo) first"),
("已存第 ","Saved #"),
(" 条到收藏(可“我的收藏”回看 / “导出”发我永久内置)"," saved — replay via My saved, or Export to send me"),
("收藏夹为空,先点“保存当前”","Saved list empty — click Save current first"),
("该收藏点不在路网附近","This saved point is not near the network"),
("收藏夹为空,无可导出","Saved list empty — nothing to export"),
("已导出 ","Exported "),
(" 条 → demo_saved.json(发我合并进后台)"," → demo_saved.json (send it to me to merge)"),
("起点:收藏 (","Origin: saved ("),
("终点:收藏","Dest: saved"),
("轮播池为空,先“保存当前”或“导入”json","Cycle pool empty — Save current or Import json first"),
("该点不在路网附近","This point is not near the network"),
("起点:轮播 (","Origin: cycle ("),
("终点:轮播","Dest: cycle"),
("浏览器收藏本来就是空的","Browser saved list is already empty"),
("清空浏览器收藏的 ","Clear "),
(" 条?(内置 Demo 与本次导入不受影响)"," saved? (built-in & imported unaffected)"),
("已清空浏览器收藏","Browser saved list cleared"),
("导入失败:需 OD 数组或场景对象 json","Import failed: need OD array or scenario object json"),
("导入失败:没有有效 OD","Import failed: no valid OD"),
("已导入 ","Imported "),
(" 条(临时,不入收藏)"," (temporary, not saved)"),
("JSON 解析失败","JSON parse failed"),
("保存当前","Save current"),
("我的收藏(","My saved("),
("导出","Export"),
("导入","Import"),
("清空","Clear"),
("人工遮荫设施(连廊/骑楼)","Artificial shading infrastructure"),
("设施小微网(连廊/骑楼)","Artificial shading infrastructure"),
("没找到 500m–1km 的示例,再点一次","No 500m–1km example found — click again"),
("分类高亮","By type"),
("统一高亮","Uniform"),
("仅原始","Original"),
("全部","All"),
("路网","Network"),
("遮荫","shaded"),("日晒","sun"),
(">中 ",">mid "),(">高 ",">high "),(">低<",">low<"),("低","low"),("中","mid"),
(">无<",">None<"),
("'起'","'A'"),("'终'","'B'"),
("// 任意点 → 最近路段垂足:返回接入端点(较近交叉口)、垂足经纬度、接入米数(点击→垂足 + 垂足→端点沿边)","// any point -> perpendicular foot on nearest edge: access node (nearer junction), foot lng/lat, access metres (click->foot + foot->node)"),
("接入步行 ","Access walk "),
("Demo 场景(点击轮换 · ","Demo scenarios (click to cycle · "),("min步行圈)","min walk)"),
("组屋→公交","HDB→Transit"),("办公→公交","Office→Transit"),("办公→餐饮","Office→Dining"),("组屋→商超","HDB→Store"),
("该场景暂无示例","No demo for this scenario"),
("'起点:'+nm+' ('","'Origin: '+nm+' ('"),
("'终点:'+nm.split('→')[1]","'Dest: '+nm.split('→')[1]"),
(" m(灰虚线,从点击点垂直接入最近路段);下列为含接入的总行程。"," m (grey dashed: perpendicular access from click to nearest path); totals below include access."),
]
for a,b in R: html=html.replace(a,b)
open(f"{WEB}\\{OUT}","w",encoding="utf-8").write(html)
# report remaining Chinese
cjk=re.findall(r'[^\x00-\x7f]', html)
ctx=set()
for m in re.finditer(r'.{0,18}[一-鿿　-〿＀-￯]+.{0,8}', html):
    s=m.group(0)
    if re.search(r'[一-鿿]',s): ctx.add(s.strip())
print("已写",OUT,"| 残留中文片段",len(ctx))
for c in sorted(ctx): print("  >>",c)
